// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-NTnPziJO8tuJN_AJ6s-vUek33kazAw',
    appId: '1:530279353524:web:b68da1be8321f089e65be1',
    messagingSenderId: '530279353524',
    projectId: 'paymatch-b2561',
    authDomain: 'paymatch-b2561.firebaseapp.com',
    storageBucket: 'paymatch-b2561.appspot.com',
    measurementId: 'G-PW589JCTGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyL9u_PUCicO68lNIb7ur2k-0WuFZQiBQ',
    appId: '1:530279353524:android:dc73db394e53ba96e65be1',
    messagingSenderId: '530279353524',
    projectId: 'paymatch-b2561',
    storageBucket: 'paymatch-b2561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQCmD4HRgkyphKjyd_Vh_ap8y_cvO6Gs',
    appId: '1:530279353524:ios:843d60d101347e82e65be1',
    messagingSenderId: '530279353524',
    projectId: 'paymatch-b2561',
    storageBucket: 'paymatch-b2561.appspot.com',
    iosClientId: '530279353524-58tb9545pga2jc21qkahf1qtv2le7r98.apps.googleusercontent.com',
    iosBundleId: 'com.example.payMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQCmD4HRgkyphKjyd_Vh_ap8y_cvO6Gs',
    appId: '1:530279353524:ios:843d60d101347e82e65be1',
    messagingSenderId: '530279353524',
    projectId: 'paymatch-b2561',
    storageBucket: 'paymatch-b2561.appspot.com',
    iosClientId: '530279353524-58tb9545pga2jc21qkahf1qtv2le7r98.apps.googleusercontent.com',
    iosBundleId: 'com.example.payMatch',
  );
}
